### PR TITLE
fix Bad Authentication error

### PR DESCRIPTION
**Pull request by ignaciocastro**
fix found on XDA forum.

### CODE REVIEW

**Review by MayurDhuri — COMMENTED** [review]
Error=BadAuthentication with new google accounts only, not with old one. Is there any fix?

**Review by kinquela — APPROVED** [review]

**Comment by umstek** [comment]
This worked until recently but now there seems to be an error. 

```
λ  python.exe .\WhatsAppGDExtract.py -sync                      
Traceback (most recent call last):                              
  File ".\WhatsAppGDExtract.py", line 206, in <module>          
    main()                                                      
  File ".\WhatsAppGDExtract.py", line 191, in main              
    runMain('sync', 'all', 0)                                   
  File ".\WhatsAppGDExtract.py", line 138, in runMain           
    drives = gDriveFileMap()                                    
  File ".\WhatsAppGDExtract.py", line 65, in gDriveFileMap      
    for result in jres['items']:                                
KeyError: 'items'                                               
```

**Comment by ArdursCorp** [comment]
Same error in post of @umstek, any solution?

**Comment by antwal** [comment]
Not working same error

**Comment by umstek** [comment]
I tried using one of the open pull requests. It worked despite the bad practice of committing dependencies.

**Comment by daddeffe** [comment]
Same error

**Pull request closed without merging**
