### PR TITLE
Actualizar settings.cfg

### PR DESCRIPTION
**Pull request by erikfersan280880**
Solicite cambios para la extraer de Google Drive especifico

### CODE REVIEW

**Comment by erikfersan280880** [comment]
https://github.com/jlord/sheetsee.js/issues/26

**Comment by erikfersan280880** [comment]
https://github.com/jlord/sheetsee.js/issues/26

**Comment by erikfersan280880** [comment]
erikfersan280880:patch-1

**Comment by erikfersan280880** [comment]
31B9648B-4B8F-47EB-A3C9-D75591ECB1C1

**Comment by Lucid36** [comment]
> Solicite cambios para la extraer de Google Drive especifico

**Pull request closed without merging**
